### ISSUE TITLE
Project setup issue

### ISSUE THREAD

**Issue by mahanthesh** [AbhinavDAIICT/qCardsOpenLibrary#1]
Hi Abhinav,

I am facing issue in project setup. I have created an android application project called TestProject and inside this, referring two dependent library modules(openCVLibrary2410 and qcardslib).
 As per integration guidelines, I have integrated all the sample code into mainactivity, but getting error on implementing interface "IdMapReader ". Compile time error showing as "Cannot resolve symbol IdMapReader". I tried to find throughout the library modules for the same, I couldn't find this interface name.

Can you please help in this.

Thanks,
Mahanthesh

**Comment by AbhinavTrips** [comment]
Hi Mahantesh,
IDMapReader must be a part of basic-setup-demo branch. Please check your current branch.


On Jan 3, 2017 5:27 PM, mahanthesh <notifications@github.com> wrote:

Hi Abhinav,

I am facing issue in project setup. I have created an android application project called TestProject and inside this, referring two dependent library modules(openCVLibrary2410 and qcardslib).
As per integration guidelines, I have integrated all the sample code into mainactivity, but getting error on implementing interface "IdMapReader ". Compile time error showing as "Cannot resolve symbol IdMapReader". I tried to find throughout the library modules for the same, I couldn't find this interface name.

Can you please help in this.

Thanks,
Mahanthesh

**Comment by mahanthesh** [comment]
Hi Abhinav,

Can you please share the exact github path to download the basic demo app.

Thanks,
Mahanthesh

**Comment by mahanthesh** [comment]
I got the path.

Thanks,
Mahanthesh

**Comment by mahanthesh** [comment]
Hi Abhinav,

     I have successfully imported the demo project
*VisualAudiencePollingOpenLibrary-basic-setup-demo* and able to build apk.
On launching app *it asked to install OpenCvManager from appstore and have
installed the same*. After that I am getting *another error "OpenCV Error:
“OpenCV was not initialized correctly. Application will be shut down”*. Can
you please help in this issue.

I have followed this
link(*http://stackoverflow.com/questions/23472173/opencv-error-opencv-was-not-initialized-correctly-application-will-be-shut-do
<http://stackoverflow.com/questions/23472173/opencv-error-opencv-was-not-initialized-correctly-application-will-be-shut-do>*)
to resolve issue, but it couldn't resolved.

Thanks,
Mahanthesh

**Comment by AbhinavTrips** [comment]
I found that some devices don't work correctly. Did you try on some other phone? What is the model you are using currently?

**Comment by mahanthesh** [comment]
Currently I am testing in Lenova K3 Note model and android version is 6.0.

**Comment by mahanthesh** [comment]
Can you please suggest some device list with specification details in which
this demo app works. It will help in verifying demo app feature quickly.

**Comment by AbhinavTrips** [comment]
Unfortunately, it'll not work on K3 Note as it is based on intel architecture. The project uses OpenCV 2.4.10 which was compiled for ARM processors. All Moto phones should work fine.

**Comment by AbhinavTrips** [comment]
upgrading to OpenCV 3.x.x should also work

**Comment by AbhinavTrips** [comment]
Marking this issue as closed

**Comment by mahanthesh** [comment]
Thanks for the support.
